// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iryabjsypmaozcfuaona.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyeWFianN5cG1hb3pjZnVhb25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NjA5MjIsImV4cCI6MjA1ODEzNjkyMn0.e44vo3D8Nm9JUwu6e0rjIVnzw0jo7y5rtygBMCBUO90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);